export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const CREATE_GROUP = "CREATE_GROUP";
export const GET_ALL_CONVERSATIONS = "GET_ALL_CONVERSATIONS";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const ADD_MEMBER_TO_GROUP = "ADD_MEMBER_TO_GROUP";
export const REMOVE_MEMBER_FROM_GROUP = "REMOVE_MEMBER_FROM_GROUP";
export const MARK_CONVERSATION_AS_READ = "MARK_CONVERSATION_AS_READ";