version: "3.9"
services:
  db:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aggregatemessagedb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  api:
    restart: on-failure
    build:
      context: .
      dockerfile: api/Dockerfile-api
    environment:
      SPRING_PROFILES_ACTIVE: prd
    ports:
      - "6910:6910"
    depends_on:
      - "db"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile-ui
    ports:
      - "5173:5173"
    depends_on:
      - api
